### ISSUE TITLE
Code Error In !help-mimic Command

### ISSUE THREAD

**Issue by NiniteGamer** [NiniteGamer/NinitebotDiscord#2]
`(node:3016) UnhandledPromiseRejectionWarning: ReferenceError: ops is not defined
    at Object.exports.run (C:\Users\theni\Desktop\NinitebotDiscord-master\NinitebotDiscord-master\commands\help-mimic.js:16:81)
    at Client.client.on (C:\Users\theni\Desktop\NinitebotDiscord-master\NinitebotDiscord-master\app.js:102:21)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver._receiver.onmessage (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\ws\lib\websocket.js:137:47)
(node:3016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by NiniteGamer** [comment]
Issue should be fixed in next update.
