### ISSUE TITLE
Code error with !help command

### ISSUE THREAD

**Issue by NiniteGamer** [NiniteGamer/NinitebotDiscord#3]
`(node:8676) UnhandledPromiseRejectionWarning: RangeError: Invalid permission string or number.
    at Function.resolve (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\util\Permissions.js:194:65)
    at Permissions.has (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\util\Permissions.js:62:35)
    at Role.hasPermission (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\structures\Role.js:171:46)
    at roles.some.r (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\structures\GuildMember.js:321:35)
    at Map.some (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\util\Collection.js:357:11)
    at GuildMember.hasPermission (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\structures\GuildMember.js:321:23)
    at Object.exports.run (C:\Users\theni\Desktop\NinitebotDiscord-master\NinitebotDiscord-master\commands\help.js:52:24)
    at Client.client.on (C:\Users\theni\Desktop\NinitebotDiscord-master\NinitebotDiscord-master\app.js:102:21)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
(node:8676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8676) UnhandledPromiseRejectionWarning: RangeError: Invalid permission string or number.
    at Function.resolve (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\util\Permissions.js:194:65)
    at Permissions.has (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\util\Permissions.js:62:35)
    at Role.hasPermission (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\structures\Role.js:171:46)
    at roles.some.r (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\structures\GuildMember.js:321:35)
    at Map.some (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\util\Collection.js:357:11)
    at GuildMember.hasPermission (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\structures\GuildMember.js:321:23)
    at Object.exports.run (C:\Users\theni\Desktop\NinitebotDiscord-master\NinitebotDiscord-master\commands\help.js:52:24)
    at Client.client.on (C:\Users\theni\Desktop\NinitebotDiscord-master\NinitebotDiscord-master\app.js:102:21)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (C:\Users\theni\Desktop\NinitebotDiscord-master\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
(node:8676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
`

**Comment by NiniteGamer** [comment]
Issue should be fixed in next update
